import NextHead from "next/head";

const Head = () => {
	return (
		<NextHead>
			<title>Loco</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/folder.png" />
		</NextHead>
	);
};

export default Head;
