import { useState } from "react";
import { GetServerSideProps } from "next";
import Head from "next/head";

import Title from "../components/title";
import Card from "../components/card";
import AddFolderButton from "../components/addFolderButton";
import AddFolderModal from "../components/addFolderModal";

import fs from "fs";
import path from "path";

export default function Home({ folders }: { folders: any }) {
	const [openModal, setOpenModal] = useState(false);
	const handleModal = () => setOpenModal(() => !openModal);

	return (
		<>
			<Head>
				<title>Loco</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="main">
				<Title text="Home" />

				{folders.map(({ hash, title, details }, i) => (
					<Card title={title} paragraph={details} hash={hash} key={i} />
				))}

				<AddFolderButton handleModal={handleModal} />
				<AddFolderModal open={openModal} handleModal={handleModal} />
			</main>
		</>
	);
}

export const getServerSideProps: GetServerSideProps = async () => {
	//* Initializing the settings file
	await fetch("http://localhost:3000/api/initialize");

	//* Getting the folders
	const data = fs.readFileSync(
		path.join(__dirname, "../../../config/settings.json")
	);
	const folders = JSON.parse(data.toString()).folders;

	const updatedFolders = await Promise.all(
		folders?.map(async ({ title, path, details }: any) => {
			const resp = await fetch("http://localhost:3000/api/link-encrypter", {
				method: "POST",
				body: JSON.stringify({ path }),
				headers: { "Content-Type": "application/json" },
			});
			const hash = await resp.json();

			return {
				title,
				details,
				hash: hash.hash,
			};
		})
	);

	return {
		props: { folders: updatedFolders },
	};
};
