import Head from "next/head";

//* Components
import Title from "../components/title";
import Card from "../components/card";

export default function Home() {
	return (
		<>
			<Head>
				<title>Loco</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-black h-[100vh] w-full text-white p-6">
				<Title text="Home" />
				<Card
					title="Card Title"
					paragraph="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, quaerat sapiente perspiciatis, velit impedit officia soluta dolore tempore consectetur error quos dolores! Mollitia harum voluptates ex labore minima veniam! Ratione!"
				/>
			</main>
		</>
	);
}
